stages:
  - deploy
  - sync

deploy_homelab:
  stage: deploy
  tags:
    - homelab 
  only:
    - main     # Se lance uniquement quand on push sur la branche main
  script:
    - echo "🚀 Démarrage du déploiement sur le Homelab..."
    
    # 0. On recrée le fichier .env avec les secrets stockés dans GitLab
    - echo "WHATSAPP_CHAT_IDS=$WHATSAPP_CHAT_IDS" >> .env
    - echo "THROTTLE_FEEDBACK=2" >> .env
    - echo "THROTTLE_FEEDBACK=0" >> .env
    
    # On ajoute le proxy (hérité des variables de groupe si configuré, sinon on le force ici par sécurité)
    # - echo "http_proxy=http://129.104.201.11:8080" >> .env
    # - echo "https_proxy=http://129.104.201.11:8080" >> .env
    
    # 1. NETTOYAGE BRUTAL (On tue par le nom explicite).
    # Le "|| true" permet de ne pas planter si le conteneur n'existe pas encore
    - docker rm -f wa-bot || true
    
    # 2. DÉPLOIEMENT PROPRE
    # --force-recreate : Oblige à refaire le conteneur
    # --remove-orphans : Supprime les vieux conteneurs qui auraient changé de nom
    - docker compose up -d --build --force-recreate --remove-orphans
    
    # 3. Nettoyage des vieilles images pour ne pas saturer le disque
    - docker image prune -f
    
    - echo "✅ Déploiement terminé ! Application accessible."

sync_github:
  stage: sync
  variables:
    GITHUB_ORG: "kpihx-labs"
    REPO_NAME: "wa-bot"
  only:
    - main
  script:
    - echo "🔍 Vérification/Création du repo sur GitHub..."
    - |
      curl -H "Authorization: token ${GITHUB_TOKEN}" \
           -X POST \
           -d "{\"name\":\"${REPO_NAME}\", \"private\":false}" \
           https://api.github.com/orgs/${GITHUB_ORG}/repos || true
    
    - echo "🔄 Synchronisation..."
    # On s'assure que le remote est bien configuré
    - git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_ORG}/${REPO_NAME}.git || git remote set-url github https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_ORG}/${REPO_NAME}.git
    
    # Correction ici : on pousse explicitement le SHA actuel vers la branche main distante
    - git push github $CI_COMMIT_SHA:refs/heads/main --force
